<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Password</name>
   <tag></tag>
   <elementGuidId>8d8b47f5-941b-4bb0-81b7-5a166b0cd9cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Password')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>nav.my-account__menu.hidden-print > ul > li:nth-of-type(2) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8eccb33e-2ac1-4318-a69f-8b5312488952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/account/password</value>
      <webElementGuid>ad660211-eb38-4634-8494-e4b599d5214b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        Password
      </value>
      <webElementGuid>0c19506c-72a1-441e-8b62-5d0b68f3f661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;my-account-page&quot;]/div[@class=&quot;my-account&quot;]/div[@class=&quot;my-account__container&quot;]/div[@class=&quot;my-account__wrapper&quot;]/nav[@class=&quot;my-account__menu hidden-print&quot;]/ul[1]/li[2]/a[1]</value>
      <webElementGuid>a3522609-2f61-473f-8250-d0227bf22514</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Password')]</value>
      <webElementGuid>f09c46b4-29e2-4a6a-8e23-a8a248ca1bbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/account/password')]</value>
      <webElementGuid>e8ff025f-6121-492c-a294-b79541b2c996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[2]/a</value>
      <webElementGuid>0f80cbed-87c1-469e-81b8-0bcc48800a74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/account/password' and (text() = '
        Password
      ' or . = '
        Password
      ')]</value>
      <webElementGuid>497d5305-ddda-4a2e-929e-363478ea2ba7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
