<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_userpassword_confirmation</name>
   <tag></tag>
   <elementGuidId>2076ea6a-ef11-4775-a5eb-27eadcd83dae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user[password_confirmation]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d5b5570d-0361-4c41-800d-1a6ca86c6dd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>34e2ab98-9e42-4237-9952-376df3f7a8c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user[password_confirmation]</value>
      <webElementGuid>0dcf79ce-4b47-4bdc-a83b-28b8ee860f31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user[password_confirmation]</value>
      <webElementGuid>9fecc6d7-88e9-4ccd-b5d4-1471176ec255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form__control</value>
      <webElementGuid>13330224-b1d0-4cae-8871-aec73b45174b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user[password_confirmation]&quot;)</value>
      <webElementGuid>06d940cc-188c-4e17-8610-5da810340ba2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user[password_confirmation]']</value>
      <webElementGuid>e744d1a6-04f9-4560-ae71-1fbbae8717e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='my_account_password_af8b589e7a']/div[2]/input</value>
      <webElementGuid>102e5dd2-2d57-43e6-bd77-9840ffcd6101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>5a4ec0ed-439b-46de-a7af-b2e70076967c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'user[password_confirmation]' and @name = 'user[password_confirmation]']</value>
      <webElementGuid>07265f23-4664-44f4-914c-d92664accbdf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
