<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign in</name>
   <tag></tag>
   <elementGuidId>5c125374-f3da-46fd-bd53-129fd58b97fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.button.button-primary.g-recaptcha</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f7c6f56b-d189-4c95-ae47-09d8eabf0fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>66ec81c3-71d2-4347-a958-0548b6abfc98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button button-primary g-recaptcha</value>
      <webElementGuid>87e8ab38-20cf-4345-84e0-da6835ef6a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sitekey</name>
      <type>Main</type>
      <value>6LdhwsclAAAAAHilv5EFCsSoCU6bTSlfgfuMFlBm</value>
      <webElementGuid>12d599b9-a1bd-4014-99b9-e819104fe37b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-callback</name>
      <type>Main</type>
      <value>onSubmit</value>
      <webElementGuid>31d01a74-be51-44d3-a415-25b096bf08ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    Sign in
  </value>
      <webElementGuid>165305a8-e2bf-4901-bb1c-f7bfd40acc15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sign_in_92567646d2&quot;)/div[@class=&quot;form__button-group&quot;]/button[@class=&quot;button button-primary g-recaptcha&quot;]</value>
      <webElementGuid>776bac71-2ea6-4b2d-b6b7-bf1ab3cf0c23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>9565189f-014d-4788-baa1-f8898e009ec1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='sign_in_92567646d2']/div[5]/button</value>
      <webElementGuid>851e61f7-eb8c-4327-92f5-0aec7904718d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/button</value>
      <webElementGuid>d613c27a-d73e-453a-af1c-603d1f28bc93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = '
    Sign in
  ' or . = '
    Sign in
  ')]</value>
      <webElementGuid>33285d2a-1708-42b1-91e5-1ed75a51a5dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
