<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_c-yuninnhjrgs2</name>
   <tag></tag>
   <elementGuidId>c5659232-cbdb-4137-ab95-c618c73c1cba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='c-yuninnhjrgs2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;c-yuninnhjrgs2&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>de4caf16-4384-4af2-88fa-72a18cd6eb64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>recaptcha challenge expires in two minutes</value>
      <webElementGuid>134f4145-92d7-4ff6-ac4d-b3223e18539f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>c-yuninnhjrgs2</value>
      <webElementGuid>9d35d39f-4ba7-422e-83fc-0a25d7cc3fbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6c35fb11-4b7f-4281-8db1-707d30c78903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>8290d66f-cf56-43bb-b3f0-ef4fd7af97f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>890de614-2a38-4ffe-954d-d07c2f118f9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/bframe?hl=en&amp;v=Ya-Cd6PbRI5ktAHEhm9JuKEu&amp;k=6LdhwsclAAAAAHilv5EFCsSoCU6bTSlfgfuMFlBm</value>
      <webElementGuid>e9c3c014-04a7-4ab5-8253-7d7e1d5dcf48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;sign-in-page&quot;]/div[5]/div[2]/iframe[1]</value>
      <webElementGuid>3056c748-770f-431d-9715-2e7e57f30381</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='c-yuninnhjrgs2']</value>
      <webElementGuid>42934302-5ce1-4527-8a35-20dd75ec241c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/iframe</value>
      <webElementGuid>3d166046-a8b2-4915-b1ea-68edb7f8c776</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'recaptcha challenge expires in two minutes' and @name = 'c-yuninnhjrgs2' and @src = 'https://www.google.com/recaptcha/api2/bframe?hl=en&amp;v=Ya-Cd6PbRI5ktAHEhm9JuKEu&amp;k=6LdhwsclAAAAAHilv5EFCsSoCU6bTSlfgfuMFlBm']</value>
      <webElementGuid>f552c277-9061-455d-8047-3f83ce7f176b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
