<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_c-c10gatak67bs</name>
   <tag></tag>
   <elementGuidId>c5659232-cbdb-4137-ab95-c618c73c1cba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='c-c10gatak67bs']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;c-c10gatak67bs&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>65691036-2a86-4f0b-b289-5279d7cc272b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>recaptcha challenge expires in two minutes</value>
      <webElementGuid>e35652d3-9797-4435-babf-162e3ff69caa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>c-c10gatak67bs</value>
      <webElementGuid>045756ae-a625-4eaa-b222-4ba811d32d94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6900ad6e-548c-461f-b160-8aef3e3fd22c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>217f7056-3308-4512-b48f-c8dc54c100d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>6e5ac0d6-1de1-4867-a08a-f98faa2f7634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/bframe?hl=en&amp;v=Ya-Cd6PbRI5ktAHEhm9JuKEu&amp;k=6LdhwsclAAAAAHilv5EFCsSoCU6bTSlfgfuMFlBm</value>
      <webElementGuid>0cd3da4e-eba4-4c60-b82b-29766e82c781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;sign-in-page&quot;]/div[5]/div[2]/iframe[1]</value>
      <webElementGuid>4b802594-3195-4d57-92a4-feb840fe630f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='c-c10gatak67bs']</value>
      <webElementGuid>b8f4980c-d8ec-4cfb-b611-94033f36847d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/iframe</value>
      <webElementGuid>b94b1335-1bed-4bb1-9e8b-4dddb93b21cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'recaptcha challenge expires in two minutes' and @name = 'c-c10gatak67bs' and @src = 'https://www.google.com/recaptcha/api2/bframe?hl=en&amp;v=Ya-Cd6PbRI5ktAHEhm9JuKEu&amp;k=6LdhwsclAAAAAHilv5EFCsSoCU6bTSlfgfuMFlBm']</value>
      <webElementGuid>958c228c-c49d-483c-aa4e-3d09f2337f1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
