<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>2a8d55d7-ea7e-4efc-b8d1-fef68ac4e068</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(2) > td.rc-imageselect-tile > div.rc-image-tile-target > div.rc-image-tile-wrapper > img.rc-image-tile-33</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>37a390ee-b712-452c-9b4e-a6492fbdf15a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>9cd5748d-b709-4568-8612-2ab40dccf47a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5t18hp6ZkHaiVTlxEJ2fJOf9xNKv03h9h8JExKOT05K-7anvniISFewCt8JkiZ8ClP1hNShhykcLuzLZH-LCi6HVGv8n_e8XOR24Sr6iH4oKnfB9qhnmf7ymVjrbSx2wNedJE7XhKASKi6cOetd4SfCb84GymJMdvTcagPHcc-fwl2ZoEcp_pyGGf3WYu0bEkEwwTQ&amp;k=6LdhwsclAAAAAHilv5EFCsSoCU6bTSlfgfuMFlBm</value>
      <webElementGuid>16b1e0e1-9a67-4c38-9600-ee0e9b369aa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>ebd79d01-a1ba-4044-85a4-3b73aee172b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Sign In - Ultimate QA/iframe_c-c10gatak67bs</value>
      <webElementGuid>4f0f6543-6a97-4d36-b73b-4efaa6b04271</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td/div/div/img</value>
      <webElementGuid>871371f5-d946-4be8-92ad-0fd972617dd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5t18hp6ZkHaiVTlxEJ2fJOf9xNKv03h9h8JExKOT05K-7anvniISFewCt8JkiZ8ClP1hNShhykcLuzLZH-LCi6HVGv8n_e8XOR24Sr6iH4oKnfB9qhnmf7ymVjrbSx2wNedJE7XhKASKi6cOetd4SfCb84GymJMdvTcagPHcc-fwl2ZoEcp_pyGGf3WYu0bEkEwwTQ&amp;k=6LdhwsclAAAAAHilv5EFCsSoCU6bTSlfgfuMFlBm')])[4]</value>
      <webElementGuid>5711c489-5c4d-414d-96c0-2ac21b9e4081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div/div/img</value>
      <webElementGuid>d75b0761-d7c9-4028-9671-78cc304ee8cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5t18hp6ZkHaiVTlxEJ2fJOf9xNKv03h9h8JExKOT05K-7anvniISFewCt8JkiZ8ClP1hNShhykcLuzLZH-LCi6HVGv8n_e8XOR24Sr6iH4oKnfB9qhnmf7ymVjrbSx2wNedJE7XhKASKi6cOetd4SfCb84GymJMdvTcagPHcc-fwl2ZoEcp_pyGGf3WYu0bEkEwwTQ&amp;k=6LdhwsclAAAAAHilv5EFCsSoCU6bTSlfgfuMFlBm']</value>
      <webElementGuid>59d72474-2b5b-4b53-a824-580027adbecd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
