<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_rc-image-tile-44</name>
   <tag></tag>
   <elementGuidId>adfaae5d-0dae-4cd8-954a-714deb5abba5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[3]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4cf7e1c3-a7d3-4d53-b777-d3da726dc7e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>b2636b28-d5a3-4653-a6e1-9e861043f25e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4Tg1pM5w-ChTilnolK1idOq4hzZETb-1If3pPXS4TPxQB_y1_hoRuLxgH4dF0rX68uqI6QWWwBEsDTOLAOX0t8otdXVJ5HddLhwk31o4IeBUehJ1Qo5G3MlRxNrWLu6SjYs8NqT48H2GjrTHoDfxINlRsw-2QLV1ft4WSgm2WQGeytfEjqIOqMBDEVHMmw2TJkMx6i&amp;k=6LdhwsclAAAAAHilv5EFCsSoCU6bTSlfgfuMFlBm</value>
      <webElementGuid>6af40e7d-ca5d-4ed8-a21e-ad6f901c8124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>602eee08-c4b9-4181-b7ce-4813240e0501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Sign In - Ultimate QA/iframe_c-c10gatak67bs</value>
      <webElementGuid>4db494bf-6902-4b7a-af66-3b438d3d1bd7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[3]/div/div/img</value>
      <webElementGuid>00fdebd5-6c0b-4ed4-9b24-4ea3b211035d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4Tg1pM5w-ChTilnolK1idOq4hzZETb-1If3pPXS4TPxQB_y1_hoRuLxgH4dF0rX68uqI6QWWwBEsDTOLAOX0t8otdXVJ5HddLhwk31o4IeBUehJ1Qo5G3MlRxNrWLu6SjYs8NqT48H2GjrTHoDfxINlRsw-2QLV1ft4WSgm2WQGeytfEjqIOqMBDEVHMmw2TJkMx6i&amp;k=6LdhwsclAAAAAHilv5EFCsSoCU6bTSlfgfuMFlBm')])[11]</value>
      <webElementGuid>31679802-8ebc-425f-af40-20279a0530e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/div/div/img</value>
      <webElementGuid>9faaf6f8-40ab-4dab-a496-5683792e93d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4Tg1pM5w-ChTilnolK1idOq4hzZETb-1If3pPXS4TPxQB_y1_hoRuLxgH4dF0rX68uqI6QWWwBEsDTOLAOX0t8otdXVJ5HddLhwk31o4IeBUehJ1Qo5G3MlRxNrWLu6SjYs8NqT48H2GjrTHoDfxINlRsw-2QLV1ft4WSgm2WQGeytfEjqIOqMBDEVHMmw2TJkMx6i&amp;k=6LdhwsclAAAAAHilv5EFCsSoCU6bTSlfgfuMFlBm']</value>
      <webElementGuid>9413c79d-5120-41b5-9069-cda4d0754404</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
