<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>2a8d55d7-ea7e-4efc-b8d1-fef68ac4e068</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[2]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ca55aa2d-69ef-4702-9403-c87ed214aad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>ea4c1059-c19d-4051-a18e-1ab585dfbffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA55RQ2DdmLIesQT7hVc58mDYQoT9Xw5aaZ8vR6EgE6bXQsSL5i2BjrXVTHhu3Kir9VNBuzw4eziYhYESqgDvmQI8vCWpWCdwhSxleqSB0ojSfmGdNNvv9CpRsHvLJEGL8bxQ7rIX9MBh8c_yjHI1tj8S2A1AmUwA4qN3ZGi7ugiNa0PvMmeEiLe0ay3O8AMZdDo6QqudtTHn1Cl-bv2-FMSGHSntg&amp;k=6LdhwsclAAAAAHilv5EFCsSoCU6bTSlfgfuMFlBm</value>
      <webElementGuid>67ab291e-2518-4a7c-9b70-0f149b7ef59f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>2b412ac9-72ec-41f9-9164-dbe19b307ec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Sign In - Ultimate QA/iframe_c-yuninnhjrgs2</value>
      <webElementGuid>109de9ef-810a-4b5a-8234-7a72c4327043</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[2]/div/div/img</value>
      <webElementGuid>9c7bd309-a326-4ad1-9fbe-3675467c8ccc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA55RQ2DdmLIesQT7hVc58mDYQoT9Xw5aaZ8vR6EgE6bXQsSL5i2BjrXVTHhu3Kir9VNBuzw4eziYhYESqgDvmQI8vCWpWCdwhSxleqSB0ojSfmGdNNvv9CpRsHvLJEGL8bxQ7rIX9MBh8c_yjHI1tj8S2A1AmUwA4qN3ZGi7ugiNa0PvMmeEiLe0ay3O8AMZdDo6QqudtTHn1Cl-bv2-FMSGHSntg&amp;k=6LdhwsclAAAAAHilv5EFCsSoCU6bTSlfgfuMFlBm')])[2]</value>
      <webElementGuid>5e7cbe40-e1fd-47ed-a86f-737960a55f50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/img</value>
      <webElementGuid>9f914ee8-7d26-4ac1-93ca-612931f32866</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA55RQ2DdmLIesQT7hVc58mDYQoT9Xw5aaZ8vR6EgE6bXQsSL5i2BjrXVTHhu3Kir9VNBuzw4eziYhYESqgDvmQI8vCWpWCdwhSxleqSB0ojSfmGdNNvv9CpRsHvLJEGL8bxQ7rIX9MBh8c_yjHI1tj8S2A1AmUwA4qN3ZGi7ugiNa0PvMmeEiLe0ay3O8AMZdDo6QqudtTHn1Cl-bv2-FMSGHSntg&amp;k=6LdhwsclAAAAAHilv5EFCsSoCU6bTSlfgfuMFlBm']</value>
      <webElementGuid>527126d7-7548-4256-9c50-dcdc2ca65d53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
