<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_rc-image-tile-44_1</name>
   <tag></tag>
   <elementGuidId>0746f414-2be3-4718-8923-7151ab5b7c82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[2]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1a2d9a9e-4939-4665-857b-7fb48ef9cf2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>06b175b3-7cba-4191-ac02-66cf1f56fd4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4Tg1pM5w-ChTilnolK1idOq4hzZETb-1If3pPXS4TPxQB_y1_hoRuLxgH4dF0rX68uqI6QWWwBEsDTOLAOX0t8otdXVJ5HddLhwk31o4IeBUehJ1Qo5G3MlRxNrWLu6SjYs8NqT48H2GjrTHoDfxINlRsw-2QLV1ft4WSgm2WQGeytfEjqIOqMBDEVHMmw2TJkMx6i&amp;k=6LdhwsclAAAAAHilv5EFCsSoCU6bTSlfgfuMFlBm&amp;id=2</value>
      <webElementGuid>18611d4a-930b-4899-978f-61f0a13423a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>02d5a3b7-eb41-43c8-832a-3b79d86dd7d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Sign In - Ultimate QA/iframe_c-yuninnhjrgs2</value>
      <webElementGuid>f92c1c78-a357-4aab-88d4-c88c1f2a10a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[2]/div/div/img</value>
      <webElementGuid>e527568b-db08-4a7e-a241-d827ca9258c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4Tg1pM5w-ChTilnolK1idOq4hzZETb-1If3pPXS4TPxQB_y1_hoRuLxgH4dF0rX68uqI6QWWwBEsDTOLAOX0t8otdXVJ5HddLhwk31o4IeBUehJ1Qo5G3MlRxNrWLu6SjYs8NqT48H2GjrTHoDfxINlRsw-2QLV1ft4WSgm2WQGeytfEjqIOqMBDEVHMmw2TJkMx6i&amp;k=6LdhwsclAAAAAHilv5EFCsSoCU6bTSlfgfuMFlBm&amp;id=2')])[10]</value>
      <webElementGuid>22be60fa-165f-4327-9109-bee1b01ee39e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/div/div/img</value>
      <webElementGuid>bbfb193c-5a8b-476b-b920-f87d3f74b502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4Tg1pM5w-ChTilnolK1idOq4hzZETb-1If3pPXS4TPxQB_y1_hoRuLxgH4dF0rX68uqI6QWWwBEsDTOLAOX0t8otdXVJ5HddLhwk31o4IeBUehJ1Qo5G3MlRxNrWLu6SjYs8NqT48H2GjrTHoDfxINlRsw-2QLV1ft4WSgm2WQGeytfEjqIOqMBDEVHMmw2TJkMx6i&amp;k=6LdhwsclAAAAAHilv5EFCsSoCU6bTSlfgfuMFlBm&amp;id=2']</value>
      <webElementGuid>278ba4d9-bde6-42b5-b8ae-ce7b7092c182</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
