<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Invalid email or password</name>
   <tag></tag>
   <elementGuidId>207729b2-4dd5-4fde-9d65-10aed740d313</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='notice']/ul/li</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.form-error__list-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>a46454ac-c960-4dff-bae2-7af0d19f8ed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-error__list-item</value>
      <webElementGuid>f428c1ce-4cc5-44d4-a344-1bbeb744491d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        Invalid email or password.
      </value>
      <webElementGuid>9ac12792-11cb-411b-b11c-e8d14c7b44c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;notice&quot;)/ul[@class=&quot;form-error__list&quot;]/li[@class=&quot;form-error__list-item&quot;]</value>
      <webElementGuid>800d3417-daf2-408d-8323-851c3a4901dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='notice']/ul/li</value>
      <webElementGuid>89013934-8ee8-46a1-97ee-62e5f967ff3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li</value>
      <webElementGuid>d241059f-b6e6-44d5-9c45-a9438a27aa35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '
        Invalid email or password.
      ' or . = '
        Invalid email or password.
      ')]</value>
      <webElementGuid>d37f3bc5-ed18-4a6c-ab99-4e98c7f3648c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
