<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_c-hizi5v5vgsy4</name>
   <tag></tag>
   <elementGuidId>96217df8-c245-4f0b-86e4-068aaaeff5fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='c-hizi5v5vgsy4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;c-hizi5v5vgsy4&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>a30831ad-9343-4933-9d41-3bd5a71ca027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>recaptcha challenge expires in two minutes</value>
      <webElementGuid>f5700e7f-c541-4280-893c-aabef5836392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>c-hizi5v5vgsy4</value>
      <webElementGuid>24706438-a0ed-492e-86f2-9a4d765afbed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1a1e93ed-c632-4a26-9c54-e94e282bf90c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>cf7d1227-8159-41af-9044-6999cefbfc25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>9c20950f-ff42-4870-89e7-728918bee0b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/bframe?hl=en&amp;v=Ya-Cd6PbRI5ktAHEhm9JuKEu&amp;k=6LdhwsclAAAAAHilv5EFCsSoCU6bTSlfgfuMFlBm</value>
      <webElementGuid>310a8ffe-a9e9-4800-a85c-5ae8848e51b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;sign-up-page&quot;]/div[5]/div[2]/iframe[1]</value>
      <webElementGuid>7c7adaf6-4639-4e35-8ef4-c8de3a9d068e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='c-hizi5v5vgsy4']</value>
      <webElementGuid>2a92c05c-5d84-408c-aced-77de90410fc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/iframe</value>
      <webElementGuid>078de2ae-cb6c-4c9b-97c0-1296cc7f3060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'recaptcha challenge expires in two minutes' and @name = 'c-hizi5v5vgsy4' and @src = 'https://www.google.com/recaptcha/api2/bframe?hl=en&amp;v=Ya-Cd6PbRI5ktAHEhm9JuKEu&amp;k=6LdhwsclAAAAAHilv5EFCsSoCU6bTSlfgfuMFlBm']</value>
      <webElementGuid>efd8c2e1-e6e9-4a31-9f34-eb8b131d898f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
